name: Run In Docker Build
on:
  push:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build.sh
      run: bash build.sh
      
    - name: to release packages
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/dist/kube*
        asset_name: kubeadm_${{ github.ref }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "compile kubeadm in github action"
      
